#  
# <center>ESHAAN SINGLA</center>
# <center>102317111</center>
# <center>3Q15</center>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
arr=arr[::-1]
print(arr)

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat_1=array1.flatten()
print(flat_1)
flat_2=array1.ravel()
print(flat_2)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1==arr2)
print(np.array_equal(arr1, arr2))


x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
x_val=np.bincount(x).argmax()
x_ind=np.where(x==x_val)
y_val=np.bincount(y).argmax()
y_ind=np.where(y==y_val)
print(x_ind,x_val)
print(y_ind,y_val)

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg)
sum_gfg=np.sum(gfg)
print(sum_gfg)
row_sum_gfg=np.sum(gfg,axis=1)
print(row_sum_gfg)
col_sum_gfg=np.sum(gfg,axis=0)
print(col_sum_gfg)

n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag_sum=np.trace(n_array)
eig_vals, eig_vecs = np.linalg.eig(n_array)
inv_matrix = np.linalg.inv(n_array)
det_matrix = np.linalg.det(n_array)
print(diag_sum)
print(eig_vals)
print(eig_vecs)
print(inv_matrix)
print(det_matrix)

p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
dot_pq=np.dot(p,q)
print(dot_pq)
print(np.cov(np.array(p).T,np.array(q).T))
p1 = [[1, 2], [2, 3], [4, 5]]
q1 = [[4, 5, 1], [6, 7, 2]]
dot_pq1=np.dot(p1,q1)
print(dot_pq1)
print(np.cov(np.array(p1).T,np.array(q1)))

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x, y)
outer = np.outer(x.flatten(), y.flatten())

from itertools import product
cartesian = np.array(list(product(x.flatten(), y.flatten())))

print(inner)
print(outer)
print(cartesian)

[5 4 6 3 2 1]
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]
[[ True  True]
 [ True  True]]
True
(array([0, 5, 7, 8, 9]),) 1
(array([0, 1, 2]),) 1
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
45
[[14]
 [16]
 [15]]
[[20  9 16]]
176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001
[[16 19]
 [26 31]]
[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]
[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]

In [ ]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
abs_val = np.abs(array)

flat_percentiles = np.percentile(array, [25, 50, 75])
col_percentiles = np.percentile(array, [25, 50, 75], axis=0)
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)

print(flat_percentiles)
print(col_percentiles)
print(row_percentiles)

mean_flat = array.mean()
median_flat = np.median(array)
std_flat = array.std()

print(mean_flat)
print(median_flat)
print(std_flat)

mean_col = array.mean(axis=0)
median_col = np.median(array, axis=0)
std_col = array.std(axis=0)

print(mean_col)
print(median_col)
print(std_col)

mean_row = array.mean(axis=1)
median_row = np.median(array, axis=1)
std_row = array.std(axis=1)

print(mean_row)
print(median_row)
print(std_row)

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floors = np.floor(a)
ceilings = np.ceil(a)
truncs = np.trunc(a)
rounds = np.round(a)

print(floors)
print(ceilings)
print(truncs)
print(rounds)

[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5
-0.5
3.8622100754188224
[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]
[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]
[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array=np.sort(array)
print(sorted_array)
sorted_indices = np.argsort(array)

print(sorted_indices)
print(sorted_array[:4])
print(sorted_array[-5:])

array2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements = array2[array2 == array2.astype(int)]
float_elements = array2[array2 != array2.astype(int)]

print(int_elements)
print(float_elements)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]
[1. 2. 3. 2.]
[1.2 2.2]


In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    if img.mode == 'RGB':
        img_array = np.array(img)
        np.savetxt('image_rgb.txt', img_array.reshape(-1, 3), fmt='%d')
        print("Saved RGB image as image_rgb.txt")
    elif img.mode == 'L':
        img_array = np.array(img)
        np.savetxt('image_gray.txt', img_array, fmt='%d')
        print("Saved Grayscale image as image_gray.txt")
    else:
        print(f"Unsupported image mode: {img.mode}")

img_to_array("image.png")
img_to_array("grey_image.png")

Saved RGB image as image_rgb.txt
Saved RGB image as image_rgb.txt
